defaults:
    - override hydra/launcher: submitit_local

# environment
task: dog-run
obs: state

env:
  _target_: dflex.envs.AntEnv
  render: False
  device: "cuda"
  num_envs: 128
  stochastic_init: True
  no_grad: True
  episode_length: 1000
  MM_caching_frequency: 16
  early_termination: True

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 50000

# training
steps: 10_000_000
seed_train_steps: 5000
batch_size: 2048 # default 256. Mine: num_envs * 32
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5 # weight of predicted next states for policy loss
lr: 3e-4
enc_lr_scale: 0.3
dec_lr_scale: 0.3
dynamics_lr: 3e-4
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000 # minimum must be 1000 x num_envs
exp_name: default
data_dir: ???

# planning
mpc: False
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
update_pi_horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -5
log_std_max: 0.5
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_dec_layers: 2
dec_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: fowm
wandb_entity: pair-diffusion
wandb_silent: false
disable_wandb: false
save_csv: false
experimental: true

# misc
save_video: false
save_agent: false
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: ???
bin_size: ???
